### ISSUE TITLE
Wrong string for collection menu (should be "Info", instead of "Collection Info")

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/Scryer#103]
2 points to enter this point:

collection view --> hamburger button
home view --> long press a collection

item in the action menu: should be "Info", instead of "Collection Info"

![photo_2018-09-07_15-08-01](https://user-images.githubusercontent.com/13250512/45203800-dd806400-b2af-11e8-8de5-4b59bbf37c47.jpg)
![photo_2018-09-07_15-08-02](https://user-images.githubusercontent.com/13250512/45203801-dd806400-b2af-11e8-89df-fe78f1cac696.jpg)

**Comment by weslyhuang** [comment]
1st level menu item so S1

**Comment by ChenMorpheus** [comment]
Allow me to put more context here as a record: Copywriter suggested "info" only since the action applies to the entire collection. However, I just checked the Indonesian version of "collection info," and it's short, so I think we could keep it "collection info" to align with other strings in the screenshot menu. I'll updated the string ID accordingly.

**Comment by weslyhuang** [comment]
invalid issue with the comment above.
