### ISSUE TITLE
"Enable screenshot button" and "Prompt to save" should be gray after disabling screenshot service

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#70]
1. Launch Scryer
2. Tap Menu -> Settings
3. Disable screenshot service

Expected 
 - "Enable screenshot button" and "Prompt to save" should be gray after disabling screenshot service
<img width="533" alt="screen shot 2018-09-05 at 2 00 17" src="https://user-images.githubusercontent.com/12458450/45074049-7b3f2c00-b114-11e8-8f77-d3f1f0fec9b2.png">

Actual 
 - 
![screenshot_20180905-135147](https://user-images.githubusercontent.com/12458450/45073888-d290cc80-b113-11e8-89b8-c0dc96306d66.png)

Scryer 1.0(173).debug
Pixel2
Android 8.1.0

**Comment by ChenMorpheus** [comment]
To highlight the difference between enabled and disabled, I've updated the UX spec to hide the options instead of making them grey. Besides, the copy was updated accordingly and reviewed by copywriter.


![image](https://user-images.githubusercontent.com/18019946/45195392-d6def600-b289-11e8-94a7-3727bee904ff.png)

**Comment by cynthiatang** [comment]
Verified: Fixed

Scryer 1.0(210).nightly
Pixel 2
Android 8.1.0
WebView 68.0.3440.91
